
version: '3.8'

services:
  zabbix-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    restart: always



  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    depends_on:
      - zabbix-db
    restart: always



  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    ports:
      - "80:8080"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Kyiv
    depends_on:
      - zabbix-server
    restart: always



  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-latest
    ports:
      - "10050:10050"
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
    restart: always



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    restart: always


  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always


  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: always
