input {
  gelf {
    port => 12201
  }
}

filter {
  if [container_name] {
    mutate {
      add_field => { "docker_container" => "%{container_name}" }
      add_field => { "docker_image" => "%{image_name}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }
}
