pipeline {
    agent {
        label 'docker-agent-1'
    }
    
    environment {
	SECRET_PASS = credentials('my-super-secret')
    }

stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning from GitHub...'
		git branch: 'main', url: 'https://github.com/AndriiMaryniak/devops-contest.git'
            }
        }
	
	stage('Build Docker Image') {
            steps {
		echo 'Building artifact from Dockerfile...'		
		dir('Task6') {
                    sh 'docker build --build-arg PASSWORD=${SECRET_PASS} -t task6-artifact:latest .'
                }
            }
        }
    }
}
